name: Create Pull Request on Commit

on:
  push:
    branches:
      - basic-paypal-apis  # Change this to the branch you want to monitor for commits

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          node -e "
          const { Octokit } = require('@octokit/rest');
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

          const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');

          (async () => {
            try {
              const { data: { default_branch } } = await octokit.repos.get({
                owner,
                repo,
              });

              const pr = await octokit.pulls.create({
                owner,
                repo,
                title: 'Automated PR from GitHub Action',
                head: 'main',  # Branch you want to merge from
                base: basic-paypal-apis,  # Branch you want to merge into
                body: 'This PR was automatically created by a GitHub Action.',
              });

              console.log(`Pull request created: ${pr.data.html_url}`);
            } catch (error) {
              console.error(`Failed to create pull request: ${error.message}`);
            }
          })();
          "
